### ISSUE TITLE
TypeError: processedInput.substring is not a function

### ISSUE THREAD

**Issue by Vaysi** [artem-solovev/regexify-string#11] opened 2021-09-19 04:33 UTC
hi 
i used couple of patterns for 1 text and I got an error 
how can I use this multiple time ? 

```
const content1 = regexifyString({
    pattern: bold_regex,
    decorator: (match, index) => {
      return (
        <span key={index} style={{fontWeight: 'bold'}}>
          ${match}
        </span>
      );
    },
    input: content
  });
const content2 = regexifyString({
    pattern: bold_regex,
    decorator: (match, index) => {
      return (
        <span key={index} style={{fontWeight: 'bold'}}>
          ${match}
        </span>
      );
    },
    input: content1
  });
```

**Comment by artem-solovev** [comment] 2021-09-19 07:22
Hi @Vaysi describe clearly
1. expected behavior
2. actual behavior (link to reproducible playground)

**Comment by Vaysi** [comment] 2021-09-19 07:49
Hi. 
1. I Expect that I can replace multiple components with multiple strings like the above code. ( I want to use components for hashtags/mentions/URLs .... ) and with your package, I only can replace one component 
2. https://stackblitz.com/edit/react-sncs5r?file=src/App.js

**Comment by artem-solovev** [comment] 2021-10-30 14:48
Dear @Vaysi , i cannot reproduce your case. Give me please reproducible example at CodeSandbox or somewhere else

**Comment by artem-solovev** [comment] 2021-10-30 14:49
Given example is empty
![image](https://user-images.githubusercontent.com/11409186/139538045-faa26157-7c85-4f82-b322-0614f5012bde.png)

**Comment by artem-solovev** [comment] 2021-10-30 14:49
Closing until reproduction will be provided

**Closed by artem-solovev** 2021-10-30 14:49 UTC
Labels: bug
